name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Define Reviewers including your user ID
      - name: Define Reviewers
        id: reviewers
        run: |
          echo "Reviewers: "
          echo "- Reviewer1"
          echo "- Reviewer2"
          echo "- Sangauppe" # Your GitHub username or user ID
          echo "- Reviewer4"
          echo "- Reviewer5"

      # Display the defined reviewers
      - name: Display Reviewers
        run: |
          echo "Reviewers: ${{ steps.reviewers.outputs.reviewers }}"
