name: Download and commit files from OneDrive

on:
  workflow_dispatch:
    inputs:
      file_url:
        description: "The URL of the file to download from OneDrive"
        required: true
      file_name:
        description: "Name of the file to be downloaded"
        required: true
      commit_message:
        description: "Commit message"
        required: true

permissions:
  contents: write

jobs:
  download_and_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Download File from OneDrive
        run: |
          wget -O "https://cognizant409983-my.sharepoint.com/:f:/g/personal/vikram_cognizant409983_onmicrosoft_com/EpekblpnXTpElOrGDaHZ2-IBNJTqi438UH3h_tnmywir2w?e=jP32zz"

      - name: Set Git Config
        run: |
          git config user.email "sangameshwar.bu9386@gmail.com"
          git config user.name "sangauppe12"

      - name: Commit Changes
        shell: bash
        run: |
          git add "${{ github.event.inputs.file_name }}"
          git commit -m "${{ github.event.inputs.commit_message }}"
          git push origin main
