name: Download, unpack, and commit the solution to git
run-name: Getting ${{ github.event.inputs.solution_name }} from OneDrive and committing
on:
  workflow_dispatch:
    inputs:
      artifact_url:
        description: "The URL of the file stored in OneDrive"
        required: true
      solution_name:
        description: "Name of the solution to be downloaded"
        required: true
      user_name: 
        description: "User name for the commit"
        required: true
      source_branch:
        description: "Branch for the solution commit"
        required: true
      target_branch:
        description: "Branch to create for the solution commit"
        required: false
      commit_message:
        description: "Message for the commit"
        required: true
permissions:
  contents: write
jobs:
  export-unpack-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Download File from OneDrive
        run: |
          wget -O "${{ github.event.inputs.solution_name }}.zip" "${{ github.event.inputs.artifact_url }}"

      - name: Unpack solution
        uses: microsoft/powerplatform-actions/unpack-solution@v0
        with:
          solution-file: "${{ github.event.inputs.solution_name }}.zip"
          solution-folder: "${{ github.event.repository.name }}"
          solution-type: 'Both'
          process-canvas-apps: false
          overwrite-files: true

      - name: Commit changes
        run: |
          rm -rf ${{ github.event.inputs.solution_name }}.zip
          rm -rf ${{ github.event.inputs.solution_name }}_managed.zip
          git config user.name "${{ github.event.inputs.user_name }}"
          git pull 
          git add --all
          git commit -am "${{ github.event.inputs.commit_message }}" --allow-empty

      - name: Push to branch
        run: |
          if [ -n "${{ github.event.inputs.target_branch }}" ]; then
              git push origin ${{ github.event.inputs.target_branch }}
          else
              git push origin ${{ github.event.inputs.source_branch }}
          fi
