name: Download solution from OneDrive
on:
  workflow_dispatch:
    inputs:
      artifact_url:
        description: "The URL of the solution file stored in OneDrive"
        required: true
      managed_artifact_url: # Add the URL for the Managed solution file
        description: "The URL of the Managed solution file stored in OneDrive"
        required: true

jobs:
  download-solution:
    runs-on: ubuntu-latest

    steps:
      - name: Download Solution Files
        run: |
          wget -O "SFProj1.zip" "https://cognizant409983-my.sharepoint.com/:u:/g/personal/vikram_cognizant409983_onmicrosoft_com/EYRolV3RHaFAmY73T4piPOMB2qNtSw1NymsV_P-gsuckLQ?e=CEdqqk"
          wget -O "SFProj1_managed.zip" "${{ github.event.inputs.managed_artifact_url }}"
